---
title: "Codebook"
author: "Jackson Yang"
date: "Jun 26 2022"
output: html_document
link: https://www.kaggle.com/code/upadorprofzs/basic-visualization-techniques/notebook 
---
```{r setup}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
```

# 1.Library & Data loading
## A. Used Libraries
```{r dv}
library(hrbrthemes)
library(tidyverse)
library(ggridges)
library(ggthemes)
library(cowplot)
library(viridis)
library(GGally)
```

## B. Database Loading
```{r}
df <- as_tibble(iris)
head(df)
```
## C. Summary of data

```{r}
summary(df)
```
# 2. Visualization Techniques
## A. Attribute histograms
**First Way**
```{r}
tema = theme(plot.title = element_text(size=10, hjust=.5),
             axis.text.x = element_text(size=12),
             axis.text.y = element_text(size=12))

theme_set(theme_clean())

sepal_length <- ggplot(data = df, mapping = aes(x = Sepal.Length)) +
    geom_histogram(bins=30, fill = "red", color = "black", size = 1.3, alpha = .8) +
    labs (title='Sepal Length Distribution',y=NULL,x=NULL) + 
    theme(plot.title = element_text(hjust=.5,size=25)) + tema

sepal_width <- ggplot(data = df, mapping = aes(x = Sepal.Width)) +
    geom_histogram(bins=30, fill = "blue", color = "black", size = 1.3, alpha = .8) +
    labs (title='Sepal Width Distribution',y=NULL,x=NULL) + 
    theme(plot.title = element_text(hjust=.5,size=25)) + tema

petal_length <- ggplot(data = df, mapping = aes(x = Petal.Length)) +
    geom_histogram(bins=30, fill = "cyan", color = "black", size = 1.3, alpha = .8) +
    labs (title='Petal Length Distribution',y=NULL,x=NULL) + 
    theme(plot.title = element_text(hjust=.5,size=25)) + tema

petal_width <- ggplot(data = df, mapping = aes(x = Petal.Width)) +
    geom_histogram(bins=30, fill = "cyan", color = "black", size = 1.3, alpha = .8) +
    labs (title='Petal Width Distribution',y=NULL,x=NULL) + 
    theme(plot.title = element_text(hjust=.5,size=25)) + tema

plot_grid(sepal_length,sepal_width,petal_length,petal_width, nrow=2)

```

**Second Way**
```{r}
tema <- theme(plot.title= element_text(size=12, hjust=.5),
              axis.text.x=element_text(size=10),
              axis.text.y=element_text(size=10))


theme_set(theme_clean())

sepallength<-ggplot(data = df, mapping = aes(x = Sepal.Length)) +
    geom_density(fill = "red", color = "black", size = 1.6, alpha = .7) +
    labs (title='Sepal Length Distribution',y=NULL,x=NULL) + 
    tema

box1 <- ggplot(data = df, mapping = aes(x = Sepal.Length)) +
    geom_boxplot(fill = "red", color = "black", size = 1.2, alpha = .7) +
    stat_boxplot(geom="errorbar") +
    labs (title='Sepal Length Box-Plot',y=NULL,x=NULL) + 
    tema


sepalwidth<-ggplot(data = df, mapping = aes(x = Sepal.Width)) +
    geom_density(fill = "purple", color = "black", size = 1.6, alpha = .7) +
    labs (title='Sepal Width Distribution',y=NULL,x=NULL) + 
    tema

box2 <- ggplot(data = df, mapping = aes(x = Sepal.Width)) +
    geom_boxplot(fill = "purple", color = "black", size = 1.2, alpha = .7) +
    stat_boxplot(geom="errorbar") +
    labs (title='Sepal Width Box-Plot',y=NULL,x=NULL) + 
    tema

petallength<-ggplot(data = df, mapping = aes(x = Petal.Length)) +
    geom_density(fill = "cyan", color = "black", size = 1.6, alpha = .7) +
    labs (title='Petal Length Distribution',y=NULL,x=NULL) + 
    tema

box3 <- ggplot(data = df, mapping = aes(x = Petal.Length)) +
    geom_boxplot(fill = "cyan", color = "black", size = 1.2, alpha = .7) +
    stat_boxplot(geom="errorbar") +
    labs (title='Petal Length Box-Plot',y=NULL,x=NULL) + 
    tema

petalwidth <-ggplot(data = df, mapping = aes(x = Petal.Width)) +
    geom_density(fill = "blue", color = "black", size = 1.6, alpha = .7) +
    labs (title='Petal Width Distribution',y=NULL,x=NULL) + 
    tema

box4 <- ggplot(data = df, mapping = aes(x = Petal.Length)) +
    geom_boxplot(fill = "blue", color = "black", size = 1.2, alpha = .7) +
    stat_boxplot(geom="errorbar") +
    labs (title='Petal Width Box-Plot',y=NULL,x=NULL) + 
    tema


plot_grid(sepallength,box1,sepalwidth,box2,petallength,box3,petalwidth,box4,nrow=4)


```
## B. Species analysis

```{r}
tema <- theme(plot.title = element_text(size=12, hjust=.5),
              legend.position='bottom',
              legend.text=element_text(size=8,face='bold'),
              legend.title=element_blank())

sepallength <- ggplot(data = df, mapping = aes(x = Sepal.Length)) +
                  geom_density(mapping = aes(fill = Species), color = "black", size = 1.5, alpha = .8) +
                  xlab("Sepal Length") +
                  ggtitle("Sepal Length by Species") +
                  tema

sepalwidth <- ggplot(data = df, mapping = aes(x = Sepal.Width)) +
                  geom_density(mapping = aes(fill = Species), color = "black", size = 1.5, alpha = .8) +
                  xlab("Sepal Width") +
                  ggtitle("Sepal Width by Species") +
                  tema

petallength <- ggplot(data = df, mapping = aes(x = Petal.Length)) +
                  geom_density(mapping = aes(fill = Species), color = "black", size = 1.5, alpha = .8) +
                  xlab("Petal Length") +
                  ggtitle("Petal Length by Species") +
                  tema

petalwidth <- ggplot(data = df, mapping = aes(x = Petal.Width)) +
                  geom_density(mapping = aes(fill = Species), color = "black", size = 1.5, alpha = .8) +
                  xlab("Petal Width") +
                  ggtitle("Petal Width by Species") +
                  tema

plot_grid(sepallength, sepalwidth, petallength, petalwidth, ncol=2, nrow=2)

```
## C. Species analysis with Ridgeline

```{r}
tema <- theme(plot.title = element_text(size=8, hjust=.1),
              legend.position='None')

sepallength <- ggplot(data = df, mapping = aes(x = Sepal.Length, y=Species)) +
                  geom_density_ridges(mapping = aes(fill = Species), color = "black", size = 1.5, alpha = .8, bandwidth = 0.181) +
                  xlab("Sepal Length") +
                  ggtitle("Sepal Length by Species") +
                  tema

sepalwidth <- ggplot(data = df, mapping = aes(x = Sepal.Width,y=Species)) +
                  geom_density_ridges(mapping = aes(fill = Species), color = "black", size = 1.5, alpha = .8,bandwidth = 0.181) +
                  xlab("Sepal Width") +
                  ggtitle("Sepal Width by Species") +
                  tema

petallength <- ggplot(data = df, mapping = aes(x = Petal.Length,y=Species)) +
                  geom_density_ridges(mapping = aes(fill = Species), color = "black", size = 1.5, alpha = .8,bandwidth = 0.181) +
                  xlab("Petal Length") +
                  ggtitle("Petal Length by Species") +
                  tema

petalwidth <- ggplot(data = df, mapping = aes(x = Petal.Width,y=Species)) +
                  geom_density_ridges(mapping = aes(fill = Species), color = "black", size = 1.5, alpha = .8,bandwidth = 0.181) +
                  xlab("Petal Width") +
                  ggtitle("Petal Width by Species") +
                  tema

plot_grid(sepallength, sepalwidth, petallength, petalwidth, ncol=2, nrow=2)

```


```{r}
sepallength <- ggplot(data = df, aes(x=Sepal.Length, y=Species, fill=Species)) +
                    geom_boxplot(size = 1.3) +
                    stat_boxplot(geom="errorbar")+
                    scale_fill_viridis(discrete = TRUE, alpha=0.6) +
                    geom_jitter(color="black", size=0.4, alpha=0.9) +
                    theme_clean() +
                    ggtitle("Sepal Length") +
                    tema

ggpairs(df, columns = 1:4, aes(colour=Species)) +
    theme_economist() +
    tema
```


```{r}
```

